management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        # Security Risk, I know :3
        include: "health,info"
      base-path: /status
info:
  app:
    name: Myney
    version: 1.0.0
    description: A tiny learning-by-doing application to simulate a basic bank.
    contact:
      name: Mohammad Noor
      url: https://www.noor.guru
      email: "moh.noor94@gmail.com"


# JDBC properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&serverTimezone=UTC
    # OMG, more security risks :3
    username: noor
    password: noor