openapi: 3.0.3

info:
  title: Myney
  description: A tiny learning-by-doing application to simulate a basic bank.
  version: 1.0.0
  contact:
    name: Mohammad Noor
    url: https://www.noor.guru
    email: moh.noor94@gmail.com

servers:
  - url: 'http://localhost:8080'
    description: Local server
  - url: 'https://test.api.myney.noor.guru'
    description: Test server [Dummy, not implemented]
  - url: 'https://api.myney.noor.guru'
    description: Production server [Dummy, not implemented]

#TODO: Add security
#security:
#  - basicAuth: []

paths:
  /v1/accounts/{id}:
    get:
      summary: Get an account
      description: Get an account
      operationId: getAccount
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          description: Account ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /v1/accounts:
    get:
      summary: Get all accounts - FOR DEMO PURPOSES ONLY
      description: Get all accounts - FOR DEMO PURPOSES ONLY
      operationId: getAccounts
      tags:
        - Accounts
        - Demo Only Purpose
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /v1/accounts/{id}/transactions:
    get:
      summary: Get all transactions of all accounts (id is ignored) - FOR DEMO PURPOSES ONLY
      description: Get all transactions of an accounts (id is ignored) - FOR DEMO PURPOSES ONLY
      operationId: getAccountTransactions
      tags:
        - Accounts
        - Transactions
        - Demo Only Purpose
      parameters:
        - name: id
          in: path
          description: Account ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a transaction
      description: Create a transaction
      operationId: createTransaction
      tags:
        - Accounts
        - Transactions
      parameters:
        - name: id
          in: path
          description: Sender Account ID
          required: true
          schema:
            type: string
      requestBody:
        description: Transaction to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /status/health:
    get:
      summary: Get health status
      description: Get health status
      operationId: getHealth
      tags:
        - Status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /status/info:
    get:
      summary: Get application info
      description: Get application info
      operationId: getInfo
      tags:
        - Status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          description: Account ID
          example: b3ef0159-6149-43b1-a54f-c75144e64931
        name:
          type: string
          description: Account name
          example: Mohammad Noor
        balance:
          type: number
          description: Account balance
          example: 25000
        currency:
          type: string
          description: Account currency
          example: USD
        createdAt:
          type: string
          format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX z
          description: Account creation date
          example: 2022-09-02T23:13:19.534+03:00 EEST
      required:
        - name
        - balance
        - currency


    Transaction:
      type: object
      properties:
        id:
          type: string
          description: Transaction ID
          example: 1b3ef0159-6149-43b1-a54f-c75144e64931
        senderAccountId:
          type: string
          description: Sender Account ID
          example: b3ef0159-6149-43b1-a54f-c75144e64931
        receiverAccountId:
          type: string
          description: Receiver Account ID
          example: f981810b-f774-475a-95a8-75090a2603db
        amount:
          type: number
          description: Transaction amount
          example: 2500
        currency:
          type: string
          description: Transaction currency
          example: USD
        createdAt:
          type: string
          format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX z
          description: Transaction creation date
          example: 2022-09-02T23:13:19.534+03:00 EEST
      required:
        - receiverAccountId
        - amount
        - currency


    TransactionRequest:
      type: object
      properties:
        receiverAccountId:
          type: string
          description: Receiver Account ID
          example: f981810b-f774-475a-95a8-75090a2603db
        amount:
          type: number
          description: Transaction amount
          example: 2500
        currency:
          type: string
          description: Transaction currency
          example: USD
      required:
        - receiverAccountId
        - amount
        - currency


    Error:
      type: object
      properties:
        timestamp:
          type: string
          format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
          description: Error timestamp
          example: 2022-09-02T23:13:19.534+03:00
        status:
          type: integer
          description: HTTP status code
          example: 500
        error:
          type: string
          description: HTTP status code description
          example: Internal Server Error
        message:
          type: string
          description: Error message
          example: "[1001] Account not found"
        path:
          type: string
          description: Request path
          example: /v1/accounts/5a434548-949a-4cfe-9096-166088d2a5805


    Health:
      type: object
      properties:
        status:
          type: string
          description: Health status
          example: UP
      required:
        - status


    Info:
      type: object
      properties:
        name:
          type: string
          description: Application name
          example: Myney
        version:
          type: string
          description: Application version
          example: 1.0.0
        description:
          type: string
          description: Application description
          example: A tiny learning-by-doing application to simulate a basic bank.
        contact:
          type: object
          properties:
            name:
              type: string
              description: Contact name
              example: Mohammad Noor
            url:
              type: string
              description: Contact URL
              example: https://www.noor.guru
            email:
              type: string
              description: Contact email
              example: moh.noor94@gmail.com